version: '3.8'
services:
  frontend:
    build: ./frontend2
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_CONNECTION_STRING="mongodb://db:27017/"
    networks:
      - app-network

  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

# Define a custom network for all services
networks:
  app-network:
    driver: bridge

# Volume for MongoDB persistence
volumes:
  mongo_data:
